libffi-3.4.4.tar.gz:
  size: 1362394
  object_id: c164da33-8575-42d5-5bbe-44de72bd40b2
  sha: sha256:d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
python-3.10/Python-3.10.19.tgz:
  size: 25919659
  object_id: 4a06a548-87b7-4c49-505d-fe9ebc5c0773
  sha: sha256:a078fb2d7a216071ebbe2e34b5f5355dd6b6e9b0cd1bacc4a41c63990c5a0eec
python-3.10/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
python-3.11/Python-3.11.13.tgz:
  size: 26581523
  object_id: 59896f2c-00ed-4920-474b-53c81ad20b3f
  sha: sha256:0f1a22f4dfd34595a29cf69ee7ea73b9eff8b1cc89d7ab29b3ab0ec04179dad8
python-3.11/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
python-3.12/Python-3.12.11.tgz:
  size: 27126512
  object_id: 807dfdba-317d-47f0-6cfa-87072286041c
  sha: sha256:7b8d59af8216044d2313de8120bfc2cc00a9bd2e542f15795e1d616c51faf3d6
python-3.12/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
sqlite-autoconf-3450200.tar.gz:
  size: 3234010
  object_id: 8b447cb8-3a5f-4a5a-782b-c5bb9462a9c8
  sha: sha256:bc9067442eedf3dd39989b5c5cfbfff37ae66cc9c99274e0c3052dc4d4a8f6ae
xz-5.6.3.tar.gz:
  size: 2279396
  object_id: 9de15318-81e4-429b-6874-9d8753ade144
  sha: sha256:b1d45295d3f71f25a4c9101bd7c8d16cb56348bbef3bbc738da0351e17c73317
